version: '3.8'

services:
  bitcoin-funds-flow-indexer:
    image: ghcr.io/blockchain-insights/blockchain_insights_base:${VERSION:-latest}
    command: [ "./scripts/run_indexer_bitcoin_funds_flow.sh" ]
    environment:
      - GRAPH_DB_URL=bolt://memgraph-funds-flow:7687
      - GRAPH_DB_USER=user
      - GRAPH_DB_PASSWORD=pwd
      - BITCOIN_NODE_RPC_URL=http://daxtohujek446464:lubosztezhujek3446457@62.210.88.131:8332
      - BLOCK_PROCESSING_TRANSACTION_THRESHOLD=1000
      - BLOCK_PROCESSING_DELAY=1
      - BITCOIN_START_BLOCK_HEIGHT=822400
    networks:
      - shared-network
    depends_on:
      - memgraph-funds-flow
    restart: unless-stopped

  memgraph-funds-flow:
    image: memgraph/memgraph-platform:2.13.0-memgraph2.13.0-lab2.10.0-mage1.13
    ports:
      - "7687:7687"
      - "7444:7444"
      - "3000:3000"
    environment:
      - MEMGRAPH_PASSFILE=/home/create_user.txt
      - MEMGRAPH=--storage-mode ${GRAPH_DB_STORAGE_MODE:-IN_MEMORY_TRANSACTIONAL} --log-level=INFO --storage-snapshot-on-exit=true --storage-snapshot-interval-sec=3600 --storage-snapshot-retention-count=6 --storage-wal-enabled=false --isolation-level=READ_COMMITTED
    volumes:
      - memgraph-funds-flow-data:/var/lib/memgraph
      - ./memgraph/create_user.txt:/home/create_user.txt
    networks:
      - shared-network
    restart: unless-stopped

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:v5.5.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    ports:
      - "9999:8080"

volumes:
  memgraph-funds-flow-data:

networks:
  shared-network:
    external: true