version: '3.8'

services:
  
  validator:
    image: ghcr.io/blockchain-insights/blockchain_insights_base:${VERSION-latest}
    command: [ "./scripts/run_validator_mainnet.sh" ]
    environment:
      - NETUID=15
      - WALLET_NAME=${WALLET_NAME:-validator}
      - WALLET_HOTKEY=${WALLET_HOTKEY:-default}
      - BITCOIN_NODE_RPC_URL=${BITCOIN_NODE_RPC_URL}
      - BITCOIN_CHEAT_FACTOR_SAMPLE_SIZE=${BITCOIN_CHEAT_FACTOR_SAMPLE_SIZE:-256}
    volumes:
      - ${BITTENSOR_VOLUME_PATH:-/bittensor}:/root/.bittensor
      - miner_db:/data
    depends_on:
      - btcli
    restart: unless-stopped

  btcli:
    image: ghcr.io/blockchain-insights/blockchain_insights_base:${VERSION-latest}
    command: [ "tail", "-f", "/dev/null" ]
    volumes:
      - ${BITTENSOR_VOLUME_PATH:-/bittensor}:/root/.bittensor
    restart: unless-stopped

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:v5.5.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  sqliteweb:
    image: tomdesinto/sqliteweb
    volumes:
      - miner_db:/data
    command: ./data/miner_registry.db

volumes:
  miner_db:
    driver: local
  bittensor:
    driver: local
