version: '3.8'

services:
  dozzle:
    ports:
      - "9999:8080"
  sqliteweb:
    image: tomdesinto/sqliteweb
    volumes:
      - miner_db:/data
    command: ./data/miner_registry.db
    ports:
      - "9998:8080"

volumes:
  miner_db:
    driver: local
  bittensor:
    driver: local