version: '3.8'

services:
  dozzle:
    ports:
      - "9999:8080"
  sqliteweb:
    ports:
      - "9998:8080"

volumes:
  node_subtensor_data:
  miner_db:
    driver: local
  bittensor:
    driver: local