version: '3.8'

services:

  node-subtensor:
    image: ghcr.io/blockchain-insights/subtensor:latest
    cpu_count: 4
    mem_limit: 40000000000
    memswap_limit: 80000000000
    ports:
      - "9944:9944"
      - "30333:30333"
      - "9933:9933"
    expose:
      - "9944"
      - "30333"
      - "9933"
    environment:
      - CARGO_HOME=/var/www/node-subtensor/.cargo
    volumes:
      - node_subtensor_data:/var/lib/node-subtensor
    command:
      - /bin/bash
      - -c
      - |
        mkdir -p /var/lib/node-subtensor && \
        ./node-subtensor \
          --base-path /var/lib/node-subtensor \
          --chain ./raw_spec.json \
          --rpc-external --rpc-cors all \
          --ws-external --no-mdns \
          --ws-max-connections 10000 --in-peers 500 --out-peers 500 \
          --bootnodes /dns/bootnode.finney.opentensor.ai/tcp/30333/ws/p2p/12D3KooWRwbMb85RWnT8DSXSYMWQtuDwh4LJzndoRrTDotTR5gDC



  validator:
    image: ghcr.io/blockchain-insights/blockchain_insights_base:${VERSION-latest}
    command: [ "./scripts/run_validator_mainnet.sh" ]
    environment:
      - NETUID=15
      - WALLET_NAME=${WALLET_NAME:-validator}
      - WALLET_HOTKEY=${WALLET_HOTKEY:-default}
      - BITCOIN_NODE_RPC_URL=${BITCOIN_NODE_RPC_URL}
      - BITCOIN_CHEAT_FACTOR_SAMPLE_SIZE=${BITCOIN_CHEAT_FACTOR_SAMPLE_SIZE:-256}
    volumes:
      - ${BITTENSOR_VOLUME_PATH:-/bittensor}:/root/.bittensor
      - miner_db:/blockchain-data-subnet/neurons/validators
    depends_on:
      - btcli
      - node-subtensor
    restart: unless-stopped

  btcli:
    image: ghcr.io/blockchain-insights/blockchain_insights_base:${VERSION-latest}
    command: [ "tail", "-f", "/dev/null" ]
    volumes:
      - ${BITTENSOR_VOLUME_PATH:-/bittensor}:/root/.bittensor
    restart: unless-stopped

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:v5.5.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  sqliteweb:
    image: tomdesinto/sqliteweb
    volumes:
      - miner_db:/data
    command: ["-d", "data/miner_registry.db"]
    depends_on:
      - validator
    restart: unless-stopped

volumes:
  node_subtensor_data:
  miner_db:
    driver: local
  bittensor:
    driver: local
