version: '3.8'

services:
  validator:
    image: ghcr.io/blockchain-insights/blockchain_insights_base:${VERSION-latest}
    command: [ "./scripts/run_validator_mainnet.sh" ]
    environment:
      - NETUID=15
      - WALLET_NAME=${WALLET_NAME:-validator}
      - WALLET_HOTKEY=${WALLET_HOTKEY:-default}
      - BITCOIN_NODE_RPC_URL=${BITCOIN_NODE_RPC_URL}
      - BITCOIN_CHEAT_FACTOR_SAMPLE_SIZE=${BITCOIN_CHEAT_FACTOR_SAMPLE_SIZE:-256}
      - SUBTENSOR_NETWORK=${SUBTENSOR_NETWORK:-local}
      - SUBTENSOR_URL=${SUBTENSOR_URL:-ws://51.158.60.18:9944}
    networks:
      - shared-network
    volumes:
      - ${BITTENSOR_VOLUME_PATH:-bittensor}:/root/.bittensor
      - miner_db:/data
    depends_on:
      - btcli
    restart: unless-stopped

  btcli:
    image: ghcr.io/blockchain-insights/blockchain_insights_base:${VERSION-latest}
    command: [ "tail", "-f", "/dev/null" ]
    volumes:
      - ${BITTENSOR_VOLUME_PATH:-bittensor}:/root/.bittensor
    restart: unless-stopped

  dozzle:
    image: amir20/dozzle:v5.5.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  sqliteweb:
    image: tomdesinto/sqliteweb
    volumes:
      - miner_db:/db
    command: miner_registry.db
    depends_on:
      - validator
    restart: unless-stopped

volumes:
  miner_db:
    driver: local
  bittensor:
    driver: local

networks:
  shared-network:
    external: true