version: '3.8'

services:
  dozzle:
    image: amir20/dozzle:v5.5.0
    ports:
      - "9999:8080"

  sqliteweb:
    image: tomdesinto/sqliteweb
    volumes:
      - miner_db:/data
    command: [ "-d", "data/miner_registry.db" ]
    ports:
      - "9998:8080"
    depends_on:
      - validator
    restart: unless-stopped

volumes:
  miner_db:
    driver: local
  bittensor:
    driver: local