version: '3.8'

services:
  validator-api-template:
    image: ${IMAGE:-blockchaininsights.azurecr.io/blockchain-data-subnet-validator-api}:${VERSION_VALIDATOR_API:-latest}
    command: [ "./scripts/run_validator_api.sh" ]
    ports:
      - "${API_PORT:-8001}:8001"
    environment:
      - NETUID=${NETUID:-15}
      - WALLET_NAME=${WALLET_NAME:-default}
      - WALLET_HOTKEY=${WALLET_HOTKEY:-default}
      - SUBTENSOR_NETWORK=${SUBTENSOR_NETWORK:-local}
      - SUBTENSOR_URL=${SUBTENSOR_URL:-ws://node-subtensor:9944}
      - DB_CONNECTION_STRING=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-changeit456$}@postgres:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-validator}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - WORKER_COUNT=${WORKER_COUNT:-16}
      - TIMEOUT=${TIMEOUT:-60}
      - RATE_LIMIT=${RATE_LIMIT:-1024}
      - TOP_RATE=${RATE_LIMIT:-0.64}
    volumes:
      - ${BITTENSOR_VOLUME_PATH:-~/.bittensor}:/root/.bittensor
      - ./config:/app/config
    restart: unless-stopped
