version: '3.8'

services:
  validator-api-template:
    image: ${IMAGE:-blockchaininsights.azurecr.io/blockchain-data-subnet-validator-api}:${VERSION_VALIDATOR_API:-latest}
    command: [
      "sh", "-c",
      "export PYTHONPATH=$PYTHONPATH:/blockchain-data-subnet-validator-api && \
      python3 main.py \
        --wallet.name ${WALLET_NAME:-default} \
        --wallet.hotkey ${WALLET_HOTKEY:-default} \
        --netuid ${NETUID:-15} \
        --subtensor.network ${SUBTENSOR_NETWORK:-local} \
        --subtensor.chain_endpoint ${SUBTENSOR_URL:-ws://node-subtensor:9944} \
        --logging.trace"
    ]
    ports:
      - "${API_PORT:-8001}:8001"
    environment:
      - NETUID=${NETUID:-15}
      - WALLET_NAME=${WALLET_NAME:-default}
      - WALLET_HOTKEY=${WALLET_HOTKEY:-default}
      - SUBTENSOR_NETWORK=${SUBTENSOR_NETWORK:-local}
      - SUBTENSOR_URL=${SUBTENSOR_URL:-ws://node-subtensor:9944}
      - ENABLE_API=${ENABLE_API:-true}
    volumes:
      - ${BITTENSOR_VOLUME_PATH:-~/.bittensor}:/root/.bittensor
      - ./config/api_key.json:/app/api_key.json
      - ./config/rate_limit.json:/app/rate_limit.json
    restart: unless-stopped
