version: '3.8'

services:
  bitcoin-core:
    image: ruimarinho/bitcoin-core:${VERSION-latest}
    command:
      -rpcuser=${RPC_USER}
      -rpcpassword=${RPC_PASSWORD}
      -rpcallowip=${RPC_ALLOW_IP:-172.16.0.0/12}
      -rpcbind=${RPC_BIND:-0.0.0.0}
      -maxconnections=${MAX_CONNECTIONS:-512}
      -printtoconsole
      -rpcworkqueue=4086
      -server=1
      -txindex=1
    ports:
      - "8332:8332"
      - "8333:8333"
    volumes:
      - "bitcoin-data:/home/bitcoin/.bitcoin"
    restart: unless-stopped

  indexer:
    image: ghcr.io/blockchain-insights/blockchain_insights_base:${VERSION-latest}
    command: [ "./scripts/run_indexer_bitcoin_funds_flow.sh" ]
    environment:
      - GRAPH_DB_URL=${GRAPH_DB_URL:-bolt://memgraph:7687}
      - GRAPH_DB_USER=${GRAPH_DB_USER}
      - GRAPH_DB_PASSWORD=${GRAPH_DB_PASSWORD}
      - BITCOIN_NODE_RPC_URL=${BITCOIN_NODE_RPC_URL:-http://${RPC_USER}:${RPC_PASSWORD}@bitcoin-core:8332}
      - BLOCK_PROCESSING_TRANSACTION_THRESHOLD=${BLOCK_PROCESSING_TRANSACTION_THRESHOLD:-1000}
      - BLOCK_PROCESSING_DELAY=${BLOCK_PROCESSING_DELAY:-1}
      - BITCOIN_START_BLOCK_HEIGHT=${BITCOIN_START_BLOCK_HEIGHT:-769787}
    depends_on:
      - memgraph
    volumes:
      - ${BITTENSOR_VOLUME_PATH:-~/.bittensor}:/root/.bittensor
    restart: unless-stopped

  memgraph:
    image: memgraph/memgraph-platform:2.13.0-memgraph2.13.0-lab2.10.0-mage1.13
    ports:
      - "7687:7687"
      - "7444:7444"
    environment:
      - MEMGRAPH_USER=${GRAPH_DB_USER}
      - MEMGRAPH_PASSWORD=${GRAPH_DB_PASSWORD}
      - MEMGRAPH=--storage-mode ${GRAPH_DB_STORAGE_MODE:-IN_MEMORY_TRANSACTIONAL} --storage-parallel-schema-recovery=true --storage-recovery-thread-count=24  --log-level=TRACE --also-log-to-stderr --storage-snapshot-on-exit=true --storage-snapshot-interval-sec=3600 --storage-snapshot-retention-count=4 --storage-wal-enabled=false --isolation-level=READ_COMMITTED --replication-restore-state-on-startup=true
    volumes:
      - memgraph-funds-flow-data:/var/lib/memgraph
    restart: unless-stopped

  miner:
    ports:
      - 8091:8091
    extends:
      file: miner-service.yml
      service: miner

  ip-blocker:
    image: ghcr.io/blockchain-insights/blockchain_insights_base:${VERSION-latest}
    command: [ "./scripts/run_ip_blocker.sh" ]
    environment:
      - WALLET_NAME=${WALLET_NAME:-default}
      - WALLET_HOTKEY=${WALLET_HOTKEY:-default}
      - NETUID=15
    volumes:
       - miner_db:/data
    network_mode: host
    privileged: true
    depends_on:
      - miner
    restart: unless-stopped

  miner2:
    environment:
      - WALLET_NAME=${WALLET_NAME2:-default2}
      - WALLET_HOTKEY=${WALLET_HOTKEY2:-default2}
    ports:
      - 8092:8092
    profiles:
      - optional
    extends:
      file: miner-service.yml
      service: miner

  miner3:
    environment:
      - WALLET_NAME=${WALLET_NAME3:-default3}
      - WALLET_HOTKEY=${WALLET_HOTKEY3:-default3}
    ports:
      - 8093:8093
    profiles:
      - optional
    extends:
      file: miner-service.yml
      service: miner

  miner4:
    environment:
      - WALLET_NAME=${WALLET_NAME4:-default4}
      - WALLET_HOTKEY=${WALLET_HOTKEY4:-default4}
    ports:
      - 8094:8094
    profiles:
      - optional
    extends:
      file: miner-service.yml
      service: miner
  
  miner5:
    environment:
      - WALLET_NAME=${WALLET_NAME5:-default5}
      - WALLET_HOTKEY=${WALLET_HOTKEY5:-default5}
    ports:
      - 8095:8095
    profiles:
      - optional
    extends:
      file: miner-service.yml
      service: miner

  miner6:
    environment:
      - WALLET_NAME=${WALLET_NAME6:-default6}
      - WALLET_HOTKEY=${WALLET_HOTKEY6:-default6}
    ports:
      - 8096:8096
    profiles:
      - optional
    extends:
      file: miner-service.yml
      service: miner

  miner7:
    environment:
      - WALLET_NAME=${WALLET_NAME7:-default7}
      - WALLET_HOTKEY=${WALLET_HOTKEY7:-default7}
    ports:
      - 8097:8097
    profiles:
      - optional
    extends:
      file: miner-service.yml
      service: miner

  miner8:
    environment:
      - WALLET_NAME=${WALLET_NAME8:-default8}
      - WALLET_HOTKEY=${WALLET_HOTKEY8:-default8}
    ports:
      - 8098:8098
    profiles:
      - optional
    extends:
      file: miner-service.yml
      service: miner
  
  miner9:
    environment:
      - WALLET_NAME=${WALLET_NAME9:-default9}
      - WALLET_HOTKEY=${WALLET_HOTKEY9:-default9}
    ports:
      - 8099:8099
    profiles:
      - optional
    extends:
      file: miner-service.yml
      service: miner

volumes:
  bitcoin-data:
    name: "bitcoin_bitcoin-data"
  memgraph-funds-flow-data:
    name: "funds_flow_memgraph-funds-flow-data"
  miner_db: