version: '3.8'

services:
  miner:
    image: ghcr.io/blockchain-insights/blockchain_insights_base:${VERSION-latest}
    command: [ "./scripts/run_miner_bitcoin_funds_flow_mainnet.sh" ]
    environment:
      - NETUID=15
      - GRAPH_DB_URL=${GRAPH_DB_URL:-bolt://memgraph:7687}
      - GRAPH_DB_USER=${GRAPH_DB_USER}
      - GRAPH_DB_PASSWORD=${GRAPH_DB_PASSWORD}
      - WALLET_NAME=${WALLET_NAME:-default}
      - WALLET_HOTKEY=${WALLET_HOTKEY:-default}
      - BITCOIN_NODE_RPC_URL=${BITCOIN_NODE_RPC_URL:-http://${RPC_USER}:${RPC_PASSWORD}@bitcoin-core:8332}
      - WAIT_FOR_SYNC=${WAIT_FOR_SYNC:-True}
      - SUBTENSOR_NETWORK=${SUBTENSOR_NETWORK:-local}
      - SUBTENSOR_URL=${SUBTENSOR_URL:-ws://51.158.60.18:9944}
      - MINER_SET_WEIGHTS=${MINER_SET_WEIGHTS:-True}
    volumes:
      - ${BITTENSOR_VOLUME_PATH:-~/.bittensor}:/root/.bittensor
      - miner_db:/data
    restart: unless-stopped