version: '3.8'

services:
  bitcoin-core:
    image: ruimarinho/bitcoin-core:${VERSION-latest}
    command:
      -printtoconsole
      -rpcallowip=${RPC_ALLOW_IF:-0.0.0.0/0}
      -rpcbind=${RPC_BIND:-0.0.0.0}
      -server=1
      -txindex=1
      -rpcuser=${RPC_USER:-bitcoinrpc}
      -rpcpassword=${RPC_PASSWORD:-rpcpassword}
    ports:
      - "8332:8332" # rpc mainnet
      - "8333:8333" # peer to peer mainnet
    volumes:
      - "bitcoin-data:/home/bitcoin/.bitcoin"
    restart: unless-stopped 

volumes:
  bitcoin-data: