version: '3.8'

services:
  bitcoin-core:
    image: ruimarinho/bitcoin-core:${VERSION:-latest}
    command:
      -printtoconsole
      -rpcallowip=${RPC_ALLOW_IP:-172.16.0.0/12}
      -rpcbind=${RPC_BIND:-0.0.0.0}
      -maxconnections=${MAX_CONNECTIONS:-512}
      -rpcworkqueue=4086
      -server=1
      -txindex=1
      -rpcuser=${RPC_USER}
      -rpcpassword=${RPC_PASSWORD}
    ports:
      - "8332:8332" # rpc mainnet
      - "8333:8333" # peer to peer mainnet
    volumes:
      - "bitcoin-data:/home/bitcoin/.bitcoin"
    networks:
      - shared-network
    restart: unless-stopped 

volumes:
  bitcoin-data:

networks:
  shared-network:
    external: true