version: '3.8'

services:
  miner:
    image: ${IMAGE:-blockchaininsights.azurecr.io/blockchain-data-subnet}:${VERSION_SUBNET:-latest}
    command: [
      "sh", "-c",
      "export PYTHONPATH=$PYTHONPATH:/blockchain-data-subnet && \
      python3 neurons/miners/miner.py \
        --wallet.name ${WALLET_NAME:-miner} \
        --wallet.hotkey ${WALLET_HOTKEY:-default1} \
        --netuid ${NETUID:-15} \
        --network ${NETWORK:-bitcoin} \
        --miner_set_weights ${MINER_SET_WEIGHTS:-True} \
        --llm_engine_url ${LLM_ENGINE_URL:-http://llm-engine:8000} \
        --subtensor.network ${SUBTENSOR_NETWORK:-local} \
        --subtensor.chain_endpoint ${SUBTENSOR_URL:-ws://node-subtensor:9944} \
        --logging.trace"
    ]
    environment:
      - NETWORK=${NETWORK:-bitcoin}
      - NETUID=${NETUID:-15}
      - GRAPH_DB_URL=${GRAPH_DB_URL:-bolt://memgraph:7687}
      - GRAPH_DB_USER=${GRAPH_DB_USER}
      - GRAPH_DB_PASSWORD=${GRAPH_DB_PASSWORD}
      - DB_CONNECTION_STRING=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-changeit456$}@postgres:5432/${POSTGRES_DB:-miner}
      - WALLET_NAME=${WALLET_NAME:-miner}
      - WALLET_HOTKEY=${WALLET_HOTKEY:-default1}
      - BITCOIN_NODE_RPC_URL=${BITCOIN_NODE_RPC_URL:-http://${RPC_USER}:${RPC_PASSWORD}@bitcoin-core:8332}
      - WAIT_FOR_SYNC=${WAIT_FOR_SYNC:-False}
      - SUBTENSOR_NETWORK=${SUBTENSOR_NETWORK:-local}
      - SUBTENSOR_URL=${SUBTENSOR_URL:-ws://node-subtensor:9944}
      - MINER_SET_WEIGHTS=${MINER_SET_WEIGHTS:-True}
      - MINER_REMOTE_CONFIG_URL=${MINER_REMOTE_CONFIG_URL:-https://chaininsightsaiprod.blob.core.windows.net/minercfg/miner.json}
      - MINER_PASSWORD=${MINER_PASSWORD}
      - LLM_ENGINE_URL=${LLM_ENGINE_URL:-http://llm-engine:8000}
    volumes:
      - ${BITTENSOR_VOLUME_PATH:-~/.bittensor}:/root/.bittensor
    restart: unless-stopped
