version: '3.8'

services:
  miner:
    image: ${IMAGE-ghcr.io/blockchain-insights/blockchain_insights_base}:${VERSION-latest}
    command: [ "./scripts/run_miner_bitcoin_funds_flow.sh" ]
    environment:
      - NETUID=${NETUID:-15}
      - GRAPH_DB_URL=${GRAPH_DB_URL:-bolt://memgraph:7687}
      - GRAPH_DB_USER=${GRAPH_DB_USER}
      - GRAPH_DB_PASSWORD=${GRAPH_DB_PASSWORD}
      - DB_CONNECTION_STRING=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-changeit456$}@postgres:5432/${POSTGRES_DB:-miner}
      - WALLET_NAME=${WALLET_NAME:-miner}
      - WALLET_HOTKEY=${WALLET_HOTKEY:-default1}
      - BITCOIN_NODE_RPC_URL=${BITCOIN_NODE_RPC_URL:-http://${RPC_USER}:${RPC_PASSWORD}@bitcoin-core:8332}
      - WAIT_FOR_SYNC=${WAIT_FOR_SYNC:-False}
      - SUBTENSOR_NETWORK=${SUBTENSOR_NETWORK:-local}
      - SUBTENSOR_URL=${SUBTENSOR_URL:-ws://node-subtensor:9944}
      - MINER_SET_WEIGHTS=${MINER_SET_WEIGHTS:-True}
      - MINER_REMOTE_CONFIG_URL=${MINER_REMOTE_CONFIG_URL:-https://subnet-15-cfg.s3.fr-par.scw.cloud/miner.json}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ${BITTENSOR_VOLUME_PATH:-~/.bittensor}:/root/.bittensor
    restart: unless-stopped
