version: '3.8'

services:
  node-subtensor:
    container_name: node-subtensor
    image: opentensor/subtensor:latest
    # Removed the ports section to prevent public exposure
    expose:
      - "9944"
      - "30333"
      - "9933"
    environment:
      - CARGO_HOME=/var/www/node-subtensor/.cargo
    networks:
      - shared-network
    command:
      - /bin/bash
      - -c
      - |
        node-subtensor \
          --base-path /tmp/blockchain \
          --chain raw_spec.json \
          --rpc-external --rpc-cors all \
          --ws-external --no-mdns \
          --ws-max-connections 10000 --in-peers 500 --out-peers 500 \
          --bootnodes /dns/bootnode.finney.opentensor.ai/tcp/30333/ws/p2p/12D3KooWRwbMb85RWnT8DSXSYMWQtuDwh4LJzndoRrTDotTR5gDC \
          --sync warp

networks:
  shared-network:
    external: true