version: '3'

services:
  node-subtensor:
    image: opentensor/subtensor:latest
    # Removed the ports section to prevent public exposure
    expose:
      - "9944"
      - "30333"
      - "9933"
    volumes:
      - node-subtensor:/tmp/blockchain
    environment:
      - CARGO_HOME=/var/www/node-subtensor/.cargo
    command:
      - /bin/bash
      - -c
      - |
        node-subtensor \
          --base-path /tmp/blockchain \
          --chain ./raw_spec.json \
          --rpc-external --rpc-cors all \
          --ws-external --no-mdns \
          --ws-max-connections 10000 --in-peers 500 --out-peers 500 \
          --bootnodes /dns/bootnode.finney.opentensor.ai/tcp/30333/ws/p2p/12D3KooWRwbMb85RWnT8DSXSYMWQtuDwh4LJzndoRrTDotTR5gDC \
          --sync warp

  ethereum-node:
    image: ethereum/client-go:latest
    container_name: geth-node
    ports:
      - 30303:30303
      - 30303:30303/udp
      - 8545:8545
      - 8546:8546
      - 8551:8551
    volumes:
      - ethereum-data:/root/.ethereum
      - ./jwt.hex:/root/.ethereum/jwt.hex
    healthcheck:
      test: [ "CMD-SHELL", "geth attach --exec eth.blockNumber" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      - --mainnet
      - --snapshot=false
      - --gcmode=archive
      - --http
      - --http.api=eth,net,web3,engine,admin
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --ws
      - --ws.origins=*
      - --ws.addr=0.0.0.0
      - --ws.api=eth,net,web3
      - --authrpc.jwtsecret=/root/.ethereum/jwt.hex
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.vhosts=*

  prysm:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain
    container_name: prysm-beaconchain
    restart: unless-stopped
    volumes:
      - ./jwt.hex:/root/.ethereum/jwt.hex
    depends_on:
      ethereum-node:
        condition: service_healthy
    ports:
      - 4000:4000
      - 3500:3500
    command:
      - --accept-terms-of-use
      - --execution-endpoint=http://ethereum-node:8551
      - --mainnet
      - --jwt-secret=/root/.ethereum/jwt.hex
      - --checkpoint-sync-url=https://beaconstate.info
      - --genesis-beacon-api-url=https://beaconstate.info

  indexer:
    image: ghcr.io/blockchain-insights/blockchain_insights_base:${VERSION:-latest}
    command: [ "./scripts/run_indexer_ethereum_funds_flow.sh" ]
    environment:
      - GRAPH_DB_URL=${GRAPH_DB_URL:-bolt://memgraph:7687}
      - GRAPH_DB_USER=${GRAPH_DB_USER}
      - GRAPH_DB_PASSWORD=${GRAPH_DB_PASSWORD}
      - ETHEREUM_NODE_RPC_URL=${ETHEREUM_NODE_RPC_URL:-http://127.0.0.1:8545}
      - ETHEREUM_SUB_START_BLOCK_HEIGHT=${ETHEREUM_SUB_START_BLOCK_HEIGHT}
      - ETHEREUM_SUB_END_BLOCK_HEIGHT=${ETHEREUM_SUB_END_BLOCK_HEIGHT}
      - ETHEREUM_SUB_THREAD_CNT=${ETHEREUM_SUB_THREAD_CNT}
    depends_on:
      - memgraph
    restart: unless-stopped
  
  memgraph:
    image: memgraph/memgraph-mage:1.15-memgraph-2.15
    ports:
      - "7687:7687"
      - "7444:7444"
    environment:
      - MEMGRAPH_USER=${GRAPH_DB_USER}
      - MEMGRAPH_PASSWORD=${GRAPH_DB_PASSWORD}
    command: ["--storage-parallel-schema-recovery=true", "--storage-recovery-thread-count=60", "--storage-gc-cycle-sec=300", "--log-level=TRACE", "--also-log-to-stderr", "--storage-snapshot-on-exit=false", "--storage-snapshot-interval-sec=14400", "--storage-snapshot-retention-count=2", "--storage-wal-enabled=true", "--isolation-level=READ_COMMITTED", "--replication-restore-state-on-startup=true", "--query-execution-timeout-sec=0"]
    volumes:
      - memgraph-data:/var/lib/memgraph
      - memgraph-log:/var/log/memgraph
      - memgraph-etc:/etc/memgraph
    restart: unless-stopped

  memgraph-lab:
    image: memgraph/lab:latest
    container_name: memgraph-lab
    ports:
      - "3000:3000"
    depends_on:
      - memgraph
    environment:
      - QUICK_CONNECT_MG_HOST=memgraph
      - QUICK_CONNECT_MG_PORT=7687

  miner1:
    environment:
      - BT_AXON_PORT=8091
    ports:
      - 8091:8091
    extends:
      file: miner-service.yml
      service: miner

  miner2:
    environment:
      - WALLET_HOTKEY=${WALLET_HOTKEY2:-default2}
      - BT_AXON_PORT=8092
    ports:
      - 8092:8092
    profiles:
      - multiminers
    extends:
      file: miner-service.yml
      service: miner

  miner3:
    environment:
      - WALLET_HOTKEY=${WALLET_HOTKEY3:-default3}
      - BT_AXON_PORT=8093
    ports:
      - 8093:8093
    profiles:
      - multiminers
    extends:
      file: miner-service.yml
      service: miner

  miner4:
    environment:
      - WALLET_HOTKEY=${WALLET_HOTKEY4:-default4}
      - BT_AXON_PORT=8094
    ports:
      - 8094:8094
    profiles:
      - multiminers
    extends:
      file: miner-service.yml
      service: miner
  
  miner5:
    environment:
      - WALLET_HOTKEY=${WALLET_HOTKEY5:-default5}
      - BT_AXON_PORT=8095
    ports:
      - 8095:8095
    profiles:
      - multiminers
    extends:
      file: miner-service.yml
      service: miner

  miner6:
    environment:
      - WALLET_HOTKEY=${WALLET_HOTKEY6:-default6}
      - BT_AXON_PORT=8096
    ports:
      - 8096:8096
    profiles:
      - multiminers
    extends:
      file: miner-service.yml
      service: miner

  miner7:
    environment:
      - WALLET_HOTKEY=${WALLET_HOTKEY7:-default7}
      - BT_AXON_PORT=8097
    ports:
      - 8097:8097
    profiles:
      - multiminers
    extends:
      file: miner-service.yml
      service: miner

  miner8:
    environment:
      - WALLET_HOTKEY=${WALLET_HOTKEY8:-default8}
      - BT_AXON_PORT=8098
    ports:
      - 8098:8098
    profiles:
      - multiminers
    extends:
      file: miner-service.yml
      service: miner

  miner9:
    environment:
      - WALLET_HOTKEY=${WALLET_HOTKEY9:-default9}
      - BT_AXON_PORT=8099
    ports:
      - 8099:8099
    profiles:
      - multiminers
    extends:
      file: miner-service.yml
      service: miner

volumes:
  node-subtensor:
    name: node-subtensor
  ethereum-data:
    name: ethereum-data
  memgraph-data:
    name: memgraph-data
  memgraph-log:
    name: memgraph-log
  memgraph-etc:
    name: memgraph-etc
  miner_db: