version: '3.8'

services:
  memgraph-funds-flow:
    ports:
      - "3000:3000"

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:v5.5.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    ports:
      - "9999:8080"

volumes:
  memgraph-funds-flow-data:
  bittensor:
    driver: local

networks:
  shared-network:
    external: true