version: '3.8'

services:
  miner:
    image: ghcr.io/blockchain-insights/blockchain_insights_base:${VERSION-latest}
    command: [ "./scripts/run_miner_ethereum_funds_flow_mainnet.sh" ]
    environment:
      - DIGEST_CHARS=${DIGEST_CHARS:-0000}
      - NETUID=${NETUID:-15}
      - GRAPH_DB_URL=${GRAPH_DB_URL:-bolt://memgraph:7687}
      - GRAPH_DB_USER=${GRAPH_DB_USER}
      - GRAPH_DB_PASSWORD=${GRAPH_DB_PASSWORD}
      - WALLET_NAME=${WALLET_NAME:-miner}
      - WALLET_HOTKEY=${WALLET_HOTKEY:-default1}
      - ETHEREUM_NODE_RPC_URL=${ETHEREUM_NODE_RPC_URL:-http://127.0.0.1:8545}
      - WAIT_FOR_SYNC=${WAIT_FOR_SYNC:-False}
      - SUBTENSOR_NETWORK=${SUBTENSOR_NETWORK:-local}
      - SUBTENSOR_URL=${SUBTENSOR_URL:-ws://node-subtensor:9944}
      - MINER_SET_WEIGHTS=${MINER_SET_WEIGHTS:-True}
      - MINER_REMOTE_CONFIG_URL=${MINER_REMOTE_CONFIG_URL:-https://subnet-15-cfg.s3.fr-par.scw.cloud/miner.json}
    volumes:
      - ${BITTENSOR_VOLUME_PATH:-~/.bittensor}:/root/.bittensor
      - miner_db:/data
    restart: unless-stopped