version: '3.8'

services:
  
  bitcoin-funds-flow-miner:
    image: ghcr.io/blockchain-insights/blockchain_insights_base:${VERSION:-latest}
    command: [ "./scripts/run_miner_bitcoin_funds_flow_mainnet.sh" ]
    environment:
      - DIGEST_CHARS=${DIGEST_CHARS:-0000}
      - GRAPH_DB_URL=${GRAPH_DB_URL:-bolt://memgraph-funds-flow:7687}
      - GRAPH_DB_USER=${GRAPH_DB_USER}
      - GRAPH_DB_PASSWORD=${GRAPH_DB_PASSWORD}
      - NETUID=15
      - WALLET_NAME=${WALLET_NAME:-miner}
      - WALLET_HOTKEY=${WALLET_HOTKEY:-default}
      - BITCOIN_NODE_RPC_URL=${BITCOIN_NODE_RPC_URL}
      - WAIT_FOR_SYNC=${WAIT_FOR_SYNC:-True}
      - SUBTENSOR_NETWORK=${SUBTENSOR_NETWORK:-local}
      - SUBTENSOR_URL=${SUBTENSOR_URL:-ws://51.158.60.18:9944}
      - MINER_SET_WEIGHTS=${MINER_SET_WEIGHTS:-True}
    volumes:
      - ${BITTENSOR_VOLUME_PATH:-bittensor}:/root/.bittensor
      - miner_db:/data
    ports:
      - "8091:8091"
    networks:
      - shared-network
    depends_on:
      - btcli
    restart: unless-stopped

  ip-blocker:
    image: ghcr.io/blockchain-insights/blockchain_insights_base:${VERSION:-latest}
    command: [ "./scripts/run_ip_blocker.sh" ]
    environment:
      - NETUID=15
      - WALLET_NAME=${WALLET_NAME:-miner}
      - WALLET_HOTKEY=${WALLET_HOTKEY:-default}
    volumes:
       - miner_db:/data
    network_mode: host
    privileged: true
    depends_on:
      - bitcoin-funds-flow-miner
    restart: unless-stopped

  btcli:
    image: ghcr.io/blockchain-insights/blockchain_insights_base:${VERSION:-latest}
    command: [ "tail", "-f", "/dev/null" ]
    volumes:
    - ${BITTENSOR_VOLUME_PATH:-bittensor}:/root/.bittensor
    restart: unless-stopped

volumes:
  miner_db:
    driver: local
  bittensor:
    driver: local

networks:
  shared-network:
    external: true