version: '3.8'

services:
  
  bitcoin-funds-flow-miner1:
    image: ghcr.io/blockchain-insights/blockchain_insights_base:${VERSION-latest}
    command: [ "./scripts/run_miner_bitcoin_funds_flow_mainnet.sh" ]
    environment:
      - GRAPH_DB_URL=${GRAPH_DB_URL:-bolt://memgraph-funds-flow:7687}
      - GRAPH_DB_USER=${GRAPH_DB_USER}
      - GRAPH_DB_PASSWORD=${GRAPH_DB_PASSWORD}
      - NETUID=15
      - WALLET_NAME=miner
      - WALLET_HOTKEY=default1
      - BITCOIN_NODE_RPC_URL=${BITCOIN_NODE_RPC_URL}
      - WAIT_FOR_SYNC=${WAIT_FOR_SYNC:-True}
      - BT_AXON_PORT=8191
      - SUBTENSOR_NETWORK=${SUBTENSOR_NETWORK:-local}
      - SUBTENSOR_URL=${SUBTENSOR_URL:-ws://51.158.60.18:9946}
    volumes:
      - ${BITTENSOR_VOLUME_PATH:-bittensor}:/root/.bittensor
      - miner_db:/data
    ports:
      - "8191:8191"
    networks:
      - shared-network
    depends_on:
      - btcli
      - memgraph-funds-flow
    restart: unless-stopped

  bitcoin-funds-flow-miner2:
    image: ghcr.io/blockchain-insights/blockchain_insights_base:${VERSION-latest}
    command: [ "./scripts/run_miner_bitcoin_funds_flow_mainnet.sh" ]
    environment:
      - GRAPH_DB_URL=${GRAPH_DB_URL:-bolt://memgraph-funds-flow:7687}
      - GRAPH_DB_USER=${GRAPH_DB_USER}
      - GRAPH_DB_PASSWORD=${GRAPH_DB_PASSWORD}
      - NETUID=15
      - WALLET_NAME=miner
      - WALLET_HOTKEY=default2
      - BITCOIN_NODE_RPC_URL=${BITCOIN_NODE_RPC_URL}
      - WAIT_FOR_SYNC=${WAIT_FOR_SYNC:-True}
      - BT_AXON_PORT=8291
      - SUBTENSOR_NETWORK=${SUBTENSOR_NETWORK:-local}
      - SUBTENSOR_URL=${SUBTENSOR_URL:-ws://51.158.60.18:9946}
    volumes:
      - ${BITTENSOR_VOLUME_PATH:-bittensor}:/root/.bittensor
      - miner_db:/data
    ports:
      - "8291:8291"
    networks:
      - shared-network
    depends_on:
      - btcli
      - memgraph-funds-flow
    restart: unless-stopped

  bitcoin-funds-flow-miner3:
    image: ghcr.io/blockchain-insights/blockchain_insights_base:${VERSION-latest}
    command: [ "./scripts/run_miner_bitcoin_funds_flow_mainnet.sh" ]
    environment:
      - GRAPH_DB_URL=${GRAPH_DB_URL:-bolt://memgraph-funds-flow:7687}
      - GRAPH_DB_USER=${GRAPH_DB_USER}
      - GRAPH_DB_PASSWORD=${GRAPH_DB_PASSWORD}
      - NETUID=15
      - WALLET_NAME=miner
      - WALLET_HOTKEY=default3
      - BITCOIN_NODE_RPC_URL=${BITCOIN_NODE_RPC_URL}
      - WAIT_FOR_SYNC=${WAIT_FOR_SYNC:-True}
      - BT_AXON_PORT=8391
      - SUBTENSOR_NETWORK=${SUBTENSOR_NETWORK:-local}
      - SUBTENSOR_URL=${SUBTENSOR_URL:-ws://51.158.60.18:9946}
    volumes:
      - ${BITTENSOR_VOLUME_PATH:-bittensor}:/root/.bittensor
      - miner_db:/data
    ports:
      - "8391:8391"
    networks:
      - shared-network
    depends_on:
      - btcli
      - memgraph-funds-flow
    restart: unless-stopped

  bitcoin-funds-flow-miner4:
    image: ghcr.io/blockchain-insights/blockchain_insights_base:${VERSION-latest}
    command: [ "./scripts/run_miner_bitcoin_funds_flow_mainnet.sh" ]
    environment:
      - GRAPH_DB_URL=${GRAPH_DB_URL:-bolt://memgraph-funds-flow:7687}
      - GRAPH_DB_USER=${GRAPH_DB_USER}
      - GRAPH_DB_PASSWORD=${GRAPH_DB_PASSWORD}
      - NETUID=15
      - WALLET_NAME=miner
      - WALLET_HOTKEY=default4
      - BITCOIN_NODE_RPC_URL=${BITCOIN_NODE_RPC_URL}
      - WAIT_FOR_SYNC=${WAIT_FOR_SYNC:-True}
      - BT_AXON_PORT=8491
      - SUBTENSOR_NETWORK=${SUBTENSOR_NETWORK:-local}
      - SUBTENSOR_URL=${SUBTENSOR_URL:-ws://51.158.60.18:9946}
    volumes:
      - ${BITTENSOR_VOLUME_PATH:-bittensor}:/root/.bittensor
      - miner_db:/data
    ports:
      - "8491:8491"
    networks:
      - shared-network
    depends_on:
      - btcli
      - memgraph-funds-flow
    restart: unless-stopped

  bitcoin-funds-flow-miner5:
    image: ghcr.io/blockchain-insights/blockchain_insights_base:${VERSION-latest}
    command: [ "./scripts/run_miner_bitcoin_funds_flow_mainnet.sh" ]
    environment:
      - GRAPH_DB_URL=${GRAPH_DB_URL:-bolt://memgraph-funds-flow:7687}
      - GRAPH_DB_USER=${GRAPH_DB_USER}
      - GRAPH_DB_PASSWORD=${GRAPH_DB_PASSWORD}
      - NETUID=15
      - WALLET_NAME=miner
      - WALLET_HOTKEY=default5
      - BITCOIN_NODE_RPC_URL=${BITCOIN_NODE_RPC_URL}
      - WAIT_FOR_SYNC=${WAIT_FOR_SYNC:-True}
      - BT_AXON_PORT=8591
      - SUBTENSOR_NETWORK=${SUBTENSOR_NETWORK:-local}
      - SUBTENSOR_URL=${SUBTENSOR_URL:-ws://51.158.60.18:9946}
    volumes:
      - ${BITTENSOR_VOLUME_PATH:-bittensor}:/root/.bittensor
      - miner_db:/data
    ports:
      - "8591:8591"
    networks:
      - shared-network
    depends_on:
      - btcli
      - memgraph-funds-flow
    restart: unless-stopped

  bitcoin-funds-flow-miner6:
    image: ghcr.io/blockchain-insights/blockchain_insights_base:${VERSION-latest}
    command: [ "./scripts/run_miner_bitcoin_funds_flow_mainnet.sh" ]
    environment:
      - GRAPH_DB_URL=${GRAPH_DB_URL:-bolt://memgraph-funds-flow:7687}
      - GRAPH_DB_USER=${GRAPH_DB_USER}
      - GRAPH_DB_PASSWORD=${GRAPH_DB_PASSWORD}
      - NETUID=15
      - WALLET_NAME=miner
      - WALLET_HOTKEY=default6
      - BITCOIN_NODE_RPC_URL=${BITCOIN_NODE_RPC_URL}
      - WAIT_FOR_SYNC=${WAIT_FOR_SYNC:-True}
      - BT_AXON_PORT=8691
      - SUBTENSOR_NETWORK=${SUBTENSOR_NETWORK:-local}
      - SUBTENSOR_URL=${SUBTENSOR_URL:-ws://51.158.60.18:9946}
    volumes:
      - ${BITTENSOR_VOLUME_PATH:-bittensor}:/root/.bittensor
      - miner_db:/data
    ports:
      - "8691:8691"
    networks:
      - shared-network
    depends_on:
      - btcli
      - memgraph-funds-flow
    restart: unless-stopped

  bitcoin-funds-flow-miner7:
    image: ghcr.io/blockchain-insights/blockchain_insights_base:${VERSION-latest}
    command: [ "./scripts/run_miner_bitcoin_funds_flow_mainnet.sh" ]
    environment:
      - GRAPH_DB_URL=${GRAPH_DB_URL:-bolt://memgraph-funds-flow:7687}
      - GRAPH_DB_USER=${GRAPH_DB_USER}
      - GRAPH_DB_PASSWORD=${GRAPH_DB_PASSWORD}
      - NETUID=15
      - WALLET_NAME=miner
      - WALLET_HOTKEY=default7
      - BITCOIN_NODE_RPC_URL=${BITCOIN_NODE_RPC_URL}
      - WAIT_FOR_SYNC=${WAIT_FOR_SYNC:-True}
      - BT_AXON_PORT=8791
      - SUBTENSOR_NETWORK=${SUBTENSOR_NETWORK:-local}
      - SUBTENSOR_URL=${SUBTENSOR_URL:-ws://51.158.60.18:9946}
    volumes:
      - ${BITTENSOR_VOLUME_PATH:-bittensor}:/root/.bittensor
      - miner_db:/data
    ports:
      - "8791:8791"
    networks:
      - shared-network
    depends_on:
      - btcli
      - memgraph-funds-flow
    restart: unless-stopped

  bitcoin-funds-flow-miner8:
    image: ghcr.io/blockchain-insights/blockchain_insights_base:${VERSION-latest}
    command: [ "./scripts/run_miner_bitcoin_funds_flow_mainnet.sh" ]
    environment:
      - GRAPH_DB_URL=${GRAPH_DB_URL:-bolt://memgraph-funds-flow:7687}
      - GRAPH_DB_USER=${GRAPH_DB_USER}
      - GRAPH_DB_PASSWORD=${GRAPH_DB_PASSWORD}
      - NETUID=15
      - WALLET_NAME=miner
      - WALLET_HOTKEY=default8
      - BITCOIN_NODE_RPC_URL=${BITCOIN_NODE_RPC_URL}
      - WAIT_FOR_SYNC=${WAIT_FOR_SYNC:-True}
      - BT_AXON_PORT=8891
      - SUBTENSOR_NETWORK=${SUBTENSOR_NETWORK:-local}
      - SUBTENSOR_URL=${SUBTENSOR_URL:-ws://51.158.60.18:9946}
    volumes:
      - ${BITTENSOR_VOLUME_PATH:-bittensor}:/root/.bittensor
      - miner_db:/data
    ports:
      - "8891:8891"
    networks:
      - shared-network
    depends_on:
      - btcli
      - memgraph-funds-flow
    restart: unless-stopped

  bitcoin-funds-flow-miner9:
    image: ghcr.io/blockchain-insights/blockchain_insights_base:${VERSION-latest}
    command: [ "./scripts/run_miner_bitcoin_funds_flow_mainnet.sh" ]
    environment:
      - GRAPH_DB_URL=${GRAPH_DB_URL:-bolt://memgraph-funds-flow:7687}
      - GRAPH_DB_USER=${GRAPH_DB_USER}
      - GRAPH_DB_PASSWORD=${GRAPH_DB_PASSWORD}
      - NETUID=15
      - WALLET_NAME=miner
      - WALLET_HOTKEY=default9
      - BITCOIN_NODE_RPC_URL=${BITCOIN_NODE_RPC_URL}
      - WAIT_FOR_SYNC=${WAIT_FOR_SYNC:-True}
      - BT_AXON_PORT=8991
      - SUBTENSOR_NETWORK=${SUBTENSOR_NETWORK:-local}
      - SUBTENSOR_URL=${SUBTENSOR_URL:-ws://51.158.60.18:9946}
    volumes:
      - ${BITTENSOR_VOLUME_PATH:-bittensor}:/root/.bittensor
      - miner_db:/data
    ports:
      - "8991:8991"
    networks:
      - shared-network
    depends_on:
      - btcli
      - memgraph-funds-flow
    restart: unless-stopped

  ip-blocker:
    image: ghcr.io/blockchain-insights/blockchain_insights_base:${VERSION-latest}
    command: [ "./scripts/run_ip_blocker.sh" ]
    environment:
      - NETUID=15
      - WALLET_NAME=${WALLET_NAME:-miner}
      - WALLET_HOTKEY=${WALLET_HOTKEY:-default1}
    volumes:
       - miner_db:/data
    network_mode: host
    privileged: true
    depends_on:
      - bitcoin-funds-flow-miner1
    restart: unless-stopped

  btcli:
    image: ghcr.io/blockchain-insights/blockchain_insights_base:${VERSION-latest}
    command: [ "tail", "-f", "/dev/null" ]
    volumes:
    - ${BITTENSOR_VOLUME_PATH:-bittensor}:/root/.bittensor
    restart: unless-stopped

volumes:
  miner_db:
    driver: local
  bittensor:
    driver: local

networks:
  shared-network:
    external: true