version: '3.8'

services:
  
  bitcoin-funds-flow-miner:
    image: ghcr.io/blockchain-insights/blockchain_insights_base:${VERSION-latest}
    command: [ "./scripts/run_miner_bitcoin_funds_flow_mainnet.sh" ]
    environment:
      - GRAPH_DB_URL=${GRAPH_DB_URL:-bolt://memgraph-funds-flow:7687}
      - GRAPH_DB_USER=${GRAPH_DB_USER}
      - GRAPH_DB_PASSWORD=${GRAPH_DB_PASSWORD}
      - NETUID=15     
      - WALLET_NAME=${WALLET_NAME:-miner}
      - WALLET_HOTKEY=${WALLET_HOTKEY:-default}
      - BLOCKCHAIR_API_KEY=${BLOCKCHAIR_API_KEY}
      - WAIT_FOR_SYNC=${WAIT_FOR_SYNC:-True}
    volumes:
      - bittensor:/root/.bittensor
    depends_on:
      - btcli
      - memgraph-funds-flow

  bitcoin-funds-flow-indexer:
    image: ghcr.io/blockchain-insights/blockchain_insights_base:${VERSION-latest}
    command: [ "./scripts/run_indexer_bitcoin_funds_flow.sh" ]
    environment:
      - GRAPH_DB_URL=${GRAPH_DB_URL:-bolt://memgraph-funds-flow:7687}
      - GRAPH_DB_USER=${GRAPH_DB_USER}
      - GRAPH_DB_PASSWORD=${GRAPH_DB_PASSWORD}
      - NODE_RPC_URL=${NODE_RPC_URL}
    networks:
      - shared-network
    depends_on:
      - memgraph-funds-flow

  btcli:
    image: ghcr.io/blockchain-insights/blockchain_insights_base:${VERSION-latest}
    command: [ "tail", "-f", "/dev/null" ]
    volumes:
      - bittensor:/root/.bittensor

  memgraph-funds-flow:
    image: memgraph/memgraph-platform
    ports:
      - "7687:7687"
      - "7444:7444"
      - "3000:3000"
    environment:
      - MGCONSOLE="--username ${GRAPH_DB_USER} --password ${GRAPH_DB_PASSWORD}"
      - MEMGRAPH_USER=${GRAPH_DB_USER}
      - MEMGRAPH_PASSWORD=${GRAPH_DB_PASSWORD}
      - MEMGRAPH=--storage-mode ${GRAPH_DB_STORAGE_MODE:-IN_MEMORY_TRANSACTIONAL}
    volumes:
      - memgraph-funds-flow-data:/var/lib/memgraph

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9999:8080"

volumes:
  memgraph-funds-flow-data:
  bittensor:
    driver: local

networks:
  shared-network:
    external: true