version: '3.8'

services:
  
  bitcoin-funds-flow-miner:
    image: ghcr.io/blockchain-insights/blockchain_insights_base:${VERSION-latest}
    command: [ "./scripts/run_miner_bitcoin_funds_flow_mainnet.sh" ]
    environment:
      - GRAPH_DB_URL=${GRAPH_DB_URL:-bolt://memgraph-funds-flow:7687}
      - GRAPH_DB_USER=${GRAPH_DB_USER}
      - GRAPH_DB_PASSWORD=${GRAPH_DB_PASSWORD}
      - NETUID=15
      - WALLET_NAME=${WALLET_NAME:-miner}
      - WALLET_HOTKEY=${WALLET_HOTKEY:-default}
      - BITCOIN_NODE_RPC_URL=${BITCOIN_NODE_RPC_URL}
      - WAIT_FOR_SYNC=${WAIT_FOR_SYNC:-True}
    volumes:
      - bittensor:/root/.bittensor
    networks:
      - shared-network
    depends_on:
      - btcli
      - memgraph-funds-flow
    restart: unless-stopped

  bitcoin-funds-flow-indexer:
    image: ghcr.io/blockchain-insights/blockchain_insights_base:${VERSION-latest}
    command: [ "./scripts/run_indexer_bitcoin_funds_flow.sh" ]
    environment:
      - GRAPH_DB_URL=${GRAPH_DB_URL:-bolt://memgraph-funds-flow:7687}
      - GRAPH_DB_USER=${GRAPH_DB_USER}
      - GRAPH_DB_PASSWORD=${GRAPH_DB_PASSWORD}
      - BITCOIN_NODE_RPC_URL=${BITCOIN_NODE_RPC_URL}
      - BLOCK_PROCESSING_TRANSACTION_THRESHOLD=${BLOCK_PROCESSING_TRANSACTION_THRESHOLD:-10}
      - BLOCK_PROCESSING_DELAY=${BLOCK_PROCESSING_DELAY:-0.1}
      - BITCOIN_START_BLOCK_HEIGHT=${BITCOIN_START_BLOCK_HEIGHT:-769787}
    networks:
      - shared-network
    depends_on:
      - memgraph-funds-flow
    restart: unless-stopped

  btcli:
    image: ghcr.io/blockchain-insights/blockchain_insights_base:${VERSION-latest}
    command: [ "tail", "-f", "/dev/null" ]
    volumes:
      - bittensor:/root/.bittensor
    restart: unless-stopped

  memgraph-funds-flow:
    image: memgraph/memgraph-platform
    ports:
      - "7687:7687"
      - "7444:7444"
      - "3000:3000"
    environment:
      - MEMGRAPH_PASSFILE=/home/create_user.txt
      - MEMGRAPH=--storage-mode ${GRAPH_DB_STORAGE_MODE:-IN_MEMORY_TRANSACTIONAL}
    volumes:
      - memgraph-funds-flow-data:/var/lib/memgraph
      - ./memgraph/create_user.txt:/home/create_user.txt
    networks:
      - shared-network
    restart: unless-stopped

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9999:8080"
    restart: unless-stopped

volumes:
  memgraph-funds-flow-data:
  bittensor:
    driver: local

networks:
  shared-network:
    external: true