version: '3.8'

services:
  bitcoin-funds-flow-indexer:
    image: ghcr.io/blockchain-insights/blockchain_insights_base:${VERSION-latest}
    command: [ "./scripts/run_indexer_bitcoin_funds_flow.sh" ]
    environment:
      - GRAPH_DB_URL=${GRAPH_DB_URL:-bolt://memgraph-funds-flow:7687}
      - GRAPH_DB_USER=${GRAPH_DB_USER}
      - GRAPH_DB_PASSWORD=${GRAPH_DB_PASSWORD}
      - BITCOIN_NODE_RPC_URL=${BITCOIN_NODE_RPC_URL}
      - BLOCK_PROCESSING_TRANSACTION_THRESHOLD=${BLOCK_PROCESSING_TRANSACTION_THRESHOLD:-1000}
      - BLOCK_PROCESSING_DELAY=${BLOCK_PROCESSING_DELAY:-1}
      - BITCOIN_START_BLOCK_HEIGHT=${BITCOIN_START_BLOCK_HEIGHT:-769787}
    networks:
      - shared-network
    depends_on:
      - memgraph-funds-flow
    restart: unless-stopped

  memgraph-funds-flow:
    image: memgraph/memgraph-platform:2.13.0-memgraph2.13.0-lab2.10.0-mage1.13
    ports:
      - "7687:7687"
      - "7444:7444"
      - "10000:10000"
    environment:
      - MEMGRAPH_PASSFILE=/home/create_user.txt
      - MEMGRAPH=--storage-mode ${GRAPH_DB_STORAGE_MODE:-IN_MEMORY_TRANSACTIONAL} --storage-parallel-schema-recovery=true --storage-recovery-thread-count=24  --log-level=TRACE --also-log-to-stderr --storage-snapshot-on-exit=true --storage-snapshot-interval-sec=3600 --storage-snapshot-retention-count=4 --storage-wal-enabled=false --isolation-level=READ_COMMITTED --replication-restore-state-on-startup=true
    volumes:
      - memgraph-funds-flow-data:/var/lib/memgraph
      - ./memgraph/create_user.txt:/home/create_user.txt
    networks:
      - shared-network
    restart: unless-stopped

volumes:
  memgraph-funds-flow-data:

networks:
  shared-network:
    external: true





    

