version: '3'

services:
  ethereum-node:
    image: ethereum/client-go:latest
    container_name: geth-node
    restart: unless-stopped
    ports:
      - 30303:30303
      - 30303:30303/udp
      - 8545:8545
      - 8546:8546
      - 8551:8551
    volumes:
      - ./:/root/.ethereum
    healthcheck:
      test: [ "CMD-SHELL", "geth attach --exec eth.blockNumber" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      - --mainnet
      - --snapshot=false
      - --gcmode=archive
      - --http
      - --http.api=eth,net,web3,engine,admin
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --ws
      - --ws.origins=*
      - --ws.addr=0.0.0.0
      - --ws.api=eth,net,web3
      - --authrpc.jwtsecret=/root/.ethereum/jwt.hex
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.vhosts=*

  prysm:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain
    container_name: prysm-beaconchain
    restart: unless-stopped
    volumes:
      - ./jwt.hex:/root/.ethereum/jwt.hex
    depends_on:
      ethereum-node:
        condition: service_healthy
    ports:
      - 4000:4000
      - 3500:3500
    command:
      - --accept-terms-of-use
      - --execution-endpoint=http://${ENDPOINT}
      - --mainnet
      - --jwt-secret=/root/.ethereum/jwt.hex
      - --checkpoint-sync-url=https://beaconstate.info
      - --genesis-beacon-api-url=https://beaconstate.info