version: '3.8'

services:
  litecoin-core:
    image: uphold/litecoin-core:${VERSION:-latest}
    command:
      -printtoconsole
      -rpcallowip=${RPC_ALLOW_IP:-172.16.0.0/12}
      -rpcbind=${RPC_BIND:-0.0.0.0}
      -maxconnections=${MAX_CONNECTIONS:-512}
      -rpcworkqueue=4086
      -server=1
      -txindex=1
      -rpcuser=${RPC_USER}
      -rpcpassword=${RPC_PASSWORD}
    ports:
      - "9332:9332" # rpc mainnet
      - "9333:9333" # peer to peer mainnet
    volumes:
      - "litecoin-data:/home/litecoin/.litecoin"
    networks:
      - shared-network
    restart: unless-stopped 

volumes:
  litecoin-data:

networks:
  shared-network:
    external: true